// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/OnlineUsers/OnlineUsersWrapper.ts
import { Component, OnInit  } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

import {OnlineUser} from "./OnlineUser"

const SUBSCRIBE_TO_ONLINE_USERS = gql`
subscription getOnlineUsers {
  online_users(order_by: {user: {name: asc }}) {
    id
    user {
      name
    }
  }
}`

@Component({  
    selector: 'OnlineUsersWrapper',  
    templateUrl: './OnlineUsersWrapper.template.html',  
  }) 

export class OnlineUsersWrapper implements OnInit {
    onlineUsers = []
    onlineIndicator: any;
    loading: boolean = true;
      
      constructor(private apollo: Apollo) {}

      ngOnInit(){
        this.onlineIndicator = setInterval(() => this.updateLastSeen(), 30000);
        this.apollo.subscribe({
          query: SUBSCRIBE_TO_ONLINE_USERS,
        }).subscribe(({ data, loading }) => {
          if(data) {
            const users = data.online_users;
            this.loading = loading;
            this.onlineUsers = [];
              users.forEach((u, index) => {
                this.onlineUsers.push(u.user)
              })
          }
          console.log('got something online users', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        }); 
      }

      updateLastSeen() {
        // Use the apollo client to run a mutation to update the last_seen value
        const UPDATE_LASTSEEN_MUTATION=gql`
          mutation updateLastSeen ($now: timestamptz!) {
            update_users(where: {}, _set: {last_seen: $now}) {
              affected_rows
            }
          }`;
        this.apollo.mutate({
          mutation: UPDATE_LASTSEEN_MUTATION,
          variables: {now: (new Date()).toISOString()}
        }).subscribe(({ data, loading }) => {
          console.log('got data lastseen', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
   
}

// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/typescript-final/src/components/OnlineUsers/OnlineUsersWrapper.tsx
import React, { useEffect } from "react";
import gql from "graphql-tag";
import { useMutation, useSubscription } from "@apollo/react-hooks";

import { UpdateLastSeenMutation, GetOnlineUsersSubscription, Online_Users } from '../../generated/graphql';

import OnlineUser from "./OnlineUser";

const UPDATE_LASTSEEN_MUTATION=gql`
  mutation updateLastSeen ($now: timestamptz!) {
    update_users(where: {}, _set: {last_seen: $now}) {
      affected_rows
    }
  }
`;

const GET_ONLINE_USERS = gql`
  subscription getOnlineUsers {
    online_users(order_by: {user: {name: asc }}) {
      id
      user {
        name
      }
    }
  }
`;

const OnlineUsersWrapper = () => {

  const [updateLastSeen] = useMutation<UpdateLastSeenMutation>(UPDATE_LASTSEEN_MUTATION);
  const { data, loading, error } = useSubscription<GetOnlineUsersSubscription>(GET_ONLINE_USERS);
  useEffect(() => {
    const onlineIndicator = setInterval(() => updateLastSeen({variables: { now: (new Date()).toISOString()}}), 20000);
    return () => clearInterval(onlineIndicator);
  });

  if(loading) {
    return (<div>Loading...</div>);
  }
  if(error || !data) {
    return(<div>Error...</div>);
  }

  const onlineUsersList = [] as Array<React.FunctionComponentElement<any>>;
  data.online_users.forEach((user:Online_Users, index:number) => {
    onlineUsersList.push(
      <OnlineUser
        user={user.user}
        key={index}
      />);
  });

  return (
    <div className="onlineUsersWrapper">
      <div className="sliderHeader">
        Online users - {data.online_users.length}
      </div>

      { onlineUsersList }
    </div>
  );

}

export default OnlineUsersWrapper;
