// community/learn/graphql-tutorials/tutorials/vue-apollo/app-final/src/components/TodoInput.vue
<template>
  <div class="formInput">
    <input 
	class="input" 
	placeholder="What needs to be done?" 
	v-model="newTodo"
	@keyup.enter="addTodo"
    />
    <i class="downArrow fa fa-angle-down" />
  </div>
</template>

<script>
  import gql from "graphql-tag";
  import { GET_MY_TODOS } from "./TodoPrivateList.vue";
  const ADD_TODO = gql`
    mutation insert_todos($todo: String!, $isPublic: Boolean!) {
      insert_todos(objects: {title: $todo, is_public: $isPublic}) {
        affected_rows
        returning {
          id
          title
          is_completed
          created_at
          is_public
        }
      }
    }
  `;
  export default {
    props: ['type'],
    data() {
      return {
        newTodo: '',
      }
    },
    methods: {
      addTodo: function () {
        // insert new todo into db
        const title = this.newTodo && this.newTodo.trim()
        const isPublic = this.type === "public" ? true : false;
        this.$apollo.mutate({
          mutation: ADD_TODO,
          variables: {
            todo: title,
            isPublic: isPublic
          },
          update: (cache, { data: { insert_todos } }) => {
            // Read the data from our cache for this query.
            try {
              if (this.type === "private") {
                const data = cache.readQuery({
                  query: GET_MY_TODOS
                });
                const insertedTodo = insert_todos.returning;
                data.todos.splice(0, 0, insertedTodo[0]);
                cache.writeQuery({
                  query: GET_MY_TODOS,
                  data
                });
              }
            } catch (e) {
              console.error(e);
            }
          },
        });
        this.newTodo = '';
      },
    }
  }
</script>

// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/app-final/src/components/Todo/TodoInput.tsx
import * as React from 'react';
import gql from 'graphql-tag';
import { useMutation } from '@apollo/react-hooks';
import { GET_MY_TODOS } from './TodoPrivateList';
import { GetMyTodosQuery, Insert_TodosMutation, Insert_TodosMutationVariables } from '../../generated/graphql';

 const ADD_TODO = gql `
  mutation insert_todos($todo: String!, $isPublic: Boolean!) {
    insert_todos(objects: {title: $todo, is_public: $isPublic}) {
      affected_rows
      returning {
        id
        title
        created_at
        is_completed
      }
    }
  }
 `;

const TodoInput = ({isPublic=false}) => {
  const [todoInput, setTodoInput] = React.useState('');
  const [addTodo] = useMutation<Insert_TodosMutation, Insert_TodosMutationVariables>(ADD_TODO);
  return (
    <form className="formInput" onSubmit={(e) => {
      e.preventDefault();
      addTodo(
        {
          variables: {todo: todoInput, isPublic },
          update(cache, { data }) {
            // do not update cache for public feed
            if (isPublic || !data) {
              return null;
            }
            const getExistingTodos = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
            // Add the new todo to the cache
            const existingTodos = getExistingTodos ? getExistingTodos.todos : [];
            const newTodo = data.insert_todos!.returning[0];
            cache.writeQuery<GetMyTodosQuery>({
              query: GET_MY_TODOS,
              data: {todos: [newTodo, ...existingTodos]}
            });
          }
        }
      );
      setTodoInput('');
    }}>
      <input
        className="input"
        placeholder="What needs to be done?"
        value={todoInput}
        onChange={e => (setTodoInput(e.target.value))}
      />
      <i className="inputMarker fa fa-angle-right" />
    </form>
  );
};

export default TodoInput;
