// community/sample-apps/realtime-chat-vue/src/components/OnlineUsers.vue
<template>
  <div :class="[isMobileView ? 'mobileonlineUsers visible-xs' : 'onlineUsers hidden-xs']">
    <div>
        <p
          :class="[isMobileView ? 'mobileuserListHeading' : 'userListHeading']"
          @click="toggleMobileView"
        >
          Online Users ({{!usersOnline ? 0 : usersOnline.length}}) 
          <i v-if="isMobileView" :class="[showMobileView ? 'fa fa-angle-down': 'fa fa-angle-up']"></i>
        </p>
        <ul v-if="(isMobileView && this.showMobileView) || !isMobileView" :class="[isMobileView ? 'mobileUserList' :'userList']">
          <li v-for="(user, key) in usersOnline" v-bind:key="key">
            {{user.username}}
          </li>
        </ul>
    </div>
  </div>
</template>

<script>
  export default {
    name: "OnlineUsers",
    data(){
      return {
        usersOnline: [],
        text: '',
        showMobileView: false
      }
    },
    methods: {
      toggleMobileView(){
        this.showMobileView = !this.showMobileView;
      }
    },
    props: ["userId", "isMobileView"],
    apollo: {
      $subscribe: {
        users: {
          query: require('../graphql/fetchOnlineUsersSubscription.gql'),
          result({ data, loading, error}) {
            if (error) {
              this.text = "Error loading online"
            }
            if (loading) {
              this.text = "Loading..."
            }
            this.usersOnline = data.user_online
          }
        }
      }
    }
  }
</script>

<style scoped>

</style>

// community/examples/react-apollo-todo/src/components/OnlineUsers/OnlineUsers.js
import React, { Component } from "react";
import { Subscription } from "react-apollo";
import gql from "graphql-tag";

const SUBSCRIPTION_ONLINE_USERS = gql`
  subscription {
    online_users(order_by: { name: asc }) {
      name
    }
  }
`;

class OnlineUsers extends Component {
  render() {
    return (
      <Subscription subscription={SUBSCRIPTION_ONLINE_USERS}>
        {({ loading, error, data }) => {
          if (loading) {
            return <div>Loading. Please wait...</div>;
          }
          if (error) {
            return <div>Error loading users</div>;
          }
          return (
            <div className="sliderMenu grayBgColor">
              <div className="sliderHeader">
                Online users - {data.online_users.length}
              </div>
              {data.online_users.map((user, index) => {
                return (
                  <div key={user.name} className="userInfo">
                    <div className="userImg">
                      <i className="far fa-user" />
                    </div>
                    <div
                      data-test={index + "_" + user.name}
                      className="userName"
                    >
                      {user.name}
                    </div>
                  </div>
                );
              })}
            </div>
          );
        }}
      </Subscription>
    );
  }
}

export default OnlineUsers;
