// community/learn/graphql-tutorials/tutorials/vue-apollo/app-final/src/components/OnlineUsers.vue
<template>
  <div class="sliderMenu grayBgColor">
    <div class="sliderHeader">
      Online users - {{ online_list.length }}
    </div>
    <div class="userInfo" v-for="user in online_list" v-bind:key="user.user.name">
      <div class="userImg">
        <i class="far fa-user" />
      </div>
      <div class="userName">
        {{ user.user.name }}
      </div>
    </div>
  </div>
</template>

<script>
  import gql from 'graphql-tag'
  const SUBSCRIPTION_ONLINE_USERS = gql`
    subscription getOnlineUsers {
      online_users(order_by: {user: {name: asc }}) {
        id
        user {
          name
        }
      }
    }
  `;
  export default {
    data() {
      return {
        online_list: [],
      };
    },
    mounted() {
      const UPDATE_LASTSEEN_MUTATION = gql`
        mutation updateLastSeen ($now: timestamptz!) {
          update_users(where: {}, _set: {last_seen: $now}) {
            affected_rows
          }
        }
      `;
      setInterval(function() {
        this.$apollo
          .mutate({
            mutation: UPDATE_LASTSEEN_MUTATION,
            variables: {
              now: new Date().toISOString()
            }
          })
          .catch(error => {
            console.error(error);
          });
      }.bind(this),30000);
    },
    apollo: {
      // Subscriptions
      $subscribe: {
        // When a user is added
        online_users: {
          query: SUBSCRIPTION_ONLINE_USERS,
          // Result hook
          result (data) {
            // Let's update the local data
            this.online_list = data.data.online_users
          },
        },
      },
    },
  }

</script>

// community/examples/react-apollo-todo/src/components/OnlineUsers/OnlineUsers.js
import React, { Component } from "react";
import { Subscription } from "react-apollo";
import gql from "graphql-tag";

const SUBSCRIPTION_ONLINE_USERS = gql`
  subscription {
    online_users(order_by: { name: asc }) {
      name
    }
  }
`;

class OnlineUsers extends Component {
  render() {
    return (
      <Subscription subscription={SUBSCRIPTION_ONLINE_USERS}>
        {({ loading, error, data }) => {
          if (loading) {
            return <div>Loading. Please wait...</div>;
          }
          if (error) {
            return <div>Error loading users</div>;
          }
          return (
            <div className="sliderMenu grayBgColor">
              <div className="sliderHeader">
                Online users - {data.online_users.length}
              </div>
              {data.online_users.map((user, index) => {
                return (
                  <div key={user.name} className="userInfo">
                    <div className="userImg">
                      <i className="far fa-user" />
                    </div>
                    <div
                      data-test={index + "_" + user.name}
                      className="userName"
                    >
                      {user.name}
                    </div>
                  </div>
                );
              })}
            </div>
          );
        }}
      </Subscription>
    );
  }
}

export default OnlineUsers;
