// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/OnlineUsers/OnlineUsersWrapper.ts
import { Component, OnInit  } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

import {OnlineUser} from "./OnlineUser"

const SUBSCRIBE_TO_ONLINE_USERS = gql`
subscription getOnlineUsers {
  online_users(order_by: {user: {name: asc }}) {
    id
    user {
      name
    }
  }
}`

@Component({  
    selector: 'OnlineUsersWrapper',  
    templateUrl: './OnlineUsersWrapper.template.html',  
  }) 

export class OnlineUsersWrapper implements OnInit {
    onlineUsers = []
    onlineIndicator: any;
    loading: boolean = true;
      
      constructor(private apollo: Apollo) {}

      ngOnInit(){
        this.onlineIndicator = setInterval(() => this.updateLastSeen(), 30000);
        this.apollo.subscribe({
          query: SUBSCRIBE_TO_ONLINE_USERS,
        }).subscribe(({ data, loading }) => {
          if(data) {
            const users = data.online_users;
            this.loading = loading;
            this.onlineUsers = [];
              users.forEach((u, index) => {
                this.onlineUsers.push(u.user)
              })
          }
          console.log('got something online users', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        }); 
      }

      updateLastSeen() {
        // Use the apollo client to run a mutation to update the last_seen value
        const UPDATE_LASTSEEN_MUTATION=gql`
          mutation updateLastSeen ($now: timestamptz!) {
            update_users(where: {}, _set: {last_seen: $now}) {
              affected_rows
            }
          }`;
        this.apollo.mutate({
          mutation: UPDATE_LASTSEEN_MUTATION,
          variables: {now: (new Date()).toISOString()}
        }).subscribe(({ data, loading }) => {
          console.log('got data lastseen', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
   
}

// community/learn/graphql-tutorials/tutorials/react-apollo/app-final/src/components/OnlineUsers/OnlineUsersWrapper.js
import React, { Component, Fragment } from 'react';
import {withApollo, Subscription} from 'react-apollo';
import gql from 'graphql-tag';

import OnlineUser from './OnlineUser';

class OnlineUsersWrapper extends Component {
  constructor(props) {
    super(props);
    this.client = props.client;
  }

  updateLastSeen() {
    // Use the apollo client to run a mutation to update the last_seen value
    const UPDATE_LASTSEEN_MUTATION=gql`
      mutation updateLastSeen ($now: timestamptz!) {
        update_users(where: {}, _set: {last_seen: $now}) {
          affected_rows
        }
      }`;
    this.client.mutate({
      mutation: UPDATE_LASTSEEN_MUTATION,
      variables: {now: (new Date()).toISOString()}
    });
  }

  componentDidMount() {
    // Every 30s, run a mutation to tell the backend that you're online
    this.onlineIndicator = setInterval(() => this.updateLastSeen(), 30000);
  }

  componentWillUnmount() {
    // Clean up
    clearInterval(this.onlineIndicator);
  }

  render() {
    return (
      <div className="onlineUsersWrapper">
        <Subscription subscription={gql`
          subscription getOnlineUsers {
            online_users(order_by: {user: {name: asc }}) {
              id
              user {
                name
              }
            }
          }`}>
          {({ loading, error, data }) => {
            if (loading) {
              return (<span>Loading...</span>);
            }
            if (error) {
              console.error(error);
              return (<span>Error!</span>);
            }
            if (data) {
              const users = data.online_users;
              const onlineUsersList = [];
              users.forEach((u, index) => {
                onlineUsersList.push(
                  <OnlineUser
                    key={index}
                    index={index}
                    user={u.user}
                  />);
              });
              return (
                <Fragment>
                  <div className="sliderHeader">
                    Online users - {users.length}
                  </div>
                  {onlineUsersList}
                </Fragment>
              );
            }
          }}
        </Subscription>
      </div>
    );
  }
}

export default withApollo(OnlineUsersWrapper);
