// community/boilerplates/react-hasura-boilerplate/advanced/src/Callback/Callback.js
import React, { Component } from 'react';
import loading from './loading.svg';

class Callback extends Component {
  render() {
    const style = {
      position: 'absolute',
      display: 'flex',
      justifyContent: 'center',
      height: '100vh',
      width: '100vw',
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: 'white',
    }

    return (
      <div style={style}>
        <img src={loading} alt="loading"/>
      </div>
    );
  }
}

export default Callback;

// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/Callback.vue
<template>
  <div class="spinner">
    <img src="../assets/loading.svg" alt="Loading">
  </div>
</template>

<script>
export default {
  methods: {
    handleLoginEvent(data) {
      window.location.href = data.state.target || "/home";
    }
  },
  created() {
    this.$auth.handleAuthentication();
  }
};
</script>

<style scoped>
.spinner {
  position: absolute;
  display: flex;
  justify-content: center;
  height: 100vh;
  width: 100vw;
  background-color: white;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>
