// community/examples/react-apollo-todo/src/components/Todo/TodoFilters.js
import React from "react";
import PropTypes from "prop-types";

const TodoFilters = ({
  todos,
  currentFilter,
  type,
  filterResults,
  clearCompleted,
  clearInProgress
}) => {
  const activeTodos = todos.filter(todo => todo.is_completed !== true);
  return (
    <div className="footerList">
      <span> {activeTodos.length} items left </span>
      <ul>
        <li onClick={() => filterResults("all")}>
          <a className={currentFilter === "all" ? "selected" : ""}>All</a>
        </li>
        <li onClick={() => filterResults("active")}>
          <a
            className={
              currentFilter === "active"
                ? "selected removePaddLeft"
                : "removePaddLeft"
            }
          >
            Active
          </a>
        </li>
        <li onClick={() => filterResults("completed")}>
          <a
            className={
              currentFilter === "completed"
                ? "selected removePaddLeft"
                : "removePaddLeft"
            }
          >
            Completed
          </a>
        </li>
      </ul>
      {type === "private" ? (
        <button onClick={() => clearCompleted(type)} className="clearComp">
          {clearInProgress ? "Clearing" : "Clear completed"}
        </button>
      ) : null}
    </div>
  );
};

TodoFilters.propTypes = {
  todos: PropTypes.array.isRequired,
  userId: PropTypes.string,
  type: PropTypes.string,
  currentFilter: PropTypes.string,
  filterResults: PropTypes.func
};

export default TodoFilters;

// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/TodoFilters.vue
<template>
  <div class="footerList">
    <span>{{ remainingTodos }} items </span>
    <ul>
      <li v-on:click="filterResults('all')">
        <a v-if="filterType === 'all' " class="selected">All</a>
        <a v-else>All</a>
      </li>
      <li v-on:click="filterResults('active')">
        <a v-if="filterType === 'active'" class="removePaddLeft selected">Active</a>
        <a v-else class="removePaddLeft">Active</a>
      </li>
      <li v-on:click="filterResults('completed')">
        <a v-if="filterType === 'completed' " class="removePaddLeft selected">Completed</a>
        <a v-else class="removePaddLeft">Completed</a>
      </li>
    </ul>
    <button v-if="type === 'private'" class="clearComp" v-on:click="clearCompleted">
      Clear Completed
    </button>
  </div>
</template>

<script>
  export default {
    props: ['type', 'remainingTodos', 'filterResults', 'filterType', 'clearCompleted'],
  }
</script>
