// community/learn/graphql-tutorials/tutorials/typescript-react-apollo/app-boilerplate/src/components/Todo/TodoPrivateWrapper.tsx
import React from "react";

import TodoInput from "./TodoInput";
import TodoPrivateList from "./TodoPrivateList";

const TodoPrivateWrapper = () => {
    return (
      <div className="todoWrapper">
        <div className="sectionHeader">Personal todos</div>
        <TodoInput />
        <TodoPrivateList />
      </div>
    );
}

export default TodoPrivateWrapper;

// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/TodoPrivateWrapper.vue
<template>
  <div class="todoWrapper">
    <TodoInput type="private" />
    <TodoPrivateList type="private" />
  </div>
</template>

<script>
import TodoInput from "../components/TodoInput";
import TodoPrivateList from "../components/TodoPrivateList";
export default {
  components: {
    TodoInput, TodoPrivateList
  }
}
</script>
