// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/TodoPublicWrapper.vue
<template>
  <div class="todoWrapper">
    <TodoInput type="public" />
    <TodoPublicList type="public" />
  </div>
</template>

<script>
import TodoInput from "../components/TodoInput";
import TodoPublicList from "../components/TodoPublicList";
export default {
  components: {
    TodoInput, TodoPublicList
  },
}
</script>

// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/typescript-boilerplate/src/components/Todo/TodoPublicWrapper.tsx
import * as React from 'react';

import TodoInput from './TodoInput';
import TodoPublicList from './TodoPublicList';

const TodoPublicWrapper = () => {
  return (
    <div className="todoWrapper">
      <div className="sectionHeader">Public feed (realtime)</div>

      <TodoInput isPublic />
      <TodoPublicList />
    </div>
  );
};

export default TodoPublicWrapper;
