// community/learn/graphql-tutorials/tutorials/react-apollo-hooks/app-boilerplate/src/components/Todo/TodoPrivateList.js
import React, { useState, Fragment } from "react";

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

const TodoPrivateList = props => {
  const [state, setState] = useState({
    filter: "all",
    clearInProgress: false,
    todos: [
      {
        id: "1",
        title: "This is private todo 1",
        is_completed: true,
        is_public: false
      },
      {
        id: "2",
        title: "This is private todo 2",
        is_completed: false,
        is_public: false
      }
    ]
  });

  const filterResults = filter => {
    setState({
      ...state,
      filter: filter
    });
  };

  const clearCompleted = () => {};

  let filteredTodos = state.todos;
  if (state.filter === "active") {
    filteredTodos = state.todos.filter(todo => todo.is_completed !== true);
  } else if (state.filter === "completed") {
    filteredTodos = state.todos.filter(todo => todo.is_completed === true);
  }

  const todoList = [];
  filteredTodos.forEach((todo, index) => {
    todoList.push(<TodoItem key={index} index={index} todo={todo} />);
  });

  return (
    <Fragment>
      <div className="todoListWrapper">
        <ul>{todoList}</ul>
      </div>

      <TodoFilters
        todos={filteredTodos}
        currentFilter={state.filter}
        filterResultsFn={filterResults}
        clearCompletedFn={clearCompleted}
        clearInProgress={state.clearInProgress}
      />
    </Fragment>
  );
};

export default TodoPrivateList;

// community/learn/graphql-tutorials/tutorials/angular-apollo/app-boilerplate/src/app/Todo/TodoPrivateList.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({  
    selector: 'TodoPrivateList',  
    templateUrl: './TodoPrivateList.template.html',  
  }) 

export class TodoPrivateList implements OnInit {
    
          filter = "all";
          clearInProgress= false;
          todos= [
            {
              id: "1",
              title: "This is private todo 1",
              is_completed: true,
              is_public: false
            },
            {
              id: "2",
              title: "This is private todo 2",
              is_completed: false,
              is_public: false
            }
          ];
          filteredTodos: any;

          ngOnInit() {
            this.filteredTodos = this.todos; 
             
          }
    
      filterResults($event) {
        this.filter = $event.filter;
        this.filteredTodos = this.todos; 
        if (this.filter === "active") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed !== true);
          } else if (this.filter === "completed") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed === true);
          }
      }
    
      clearCompleted() {}
}
