// community/learn/graphql-tutorials/tutorials/react-apollo-hooks/app-boilerplate/src/components/Todo/TodoItem.js
import React from "react";

const TodoItem = ({ index, todo }) => {
  const removeTodo = e => {
    e.preventDefault();
    e.stopPropagation();
  };

  const toggleTodo = () => {};

  return (
    <li>
      <div className="view">
        <div className="round">
          <input
            checked={todo.is_completed}
            type="checkbox"
            id={todo.id}
            onChange={toggleTodo}
          />
          <label htmlFor={todo.id} />
        </div>
      </div>

      <div className={"labelContent" + (todo.is_completed ? " completed" : "")}>
        <div>{todo.title}</div>
      </div>

      <button className="closeBtn" onClick={removeTodo}>
        x
      </button>
    </li>
  );
};

export default TodoItem;

// community/learn/graphql-tutorials/tutorials/angular-apollo/app-boilerplate/src/app/Todo/TodoItem.ts
import { Component, OnInit, Input } from '@angular/core'; 

@Component({  
    selector: 'TodoItem',  
    templateUrl: './TodoItem.template.html',  
  }) 

export class TodoItem {
    @Input('todo') todo: any;
    
    removeTodo = (e) => {
        e.preventDefault();
        e.stopPropagation();
      };
    
      toggleTodo = () => {};
}
