// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoPrivateList.ts
import { Component, OnInit  } from '@angular/core';

import {TodoItem} from "./TodoItem";
import {TodoFilters} from "./TodoFilters";
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

export const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
 }`;

@Component({  
    selector: 'TodoPrivateList',  
    templateUrl: './TodoPrivateList.template.html'
  }) 

export class TodoPrivateList implements OnInit {
    
          filter = "all";
          clearInProgress= false;
          todos= [];
          filteredTodos: any;
          loading: boolean = true;


          constructor(private apollo: Apollo) {}

          ngOnInit() {
            this.apollo.watchQuery<any>({
              query: GET_MY_TODOS
            })
              .valueChanges
              .subscribe(({ data, loading }) => {
                this.loading = loading;
                this.todos = data.todos;
                this.filteredTodos = this.todos; 
              });
          }
    
      filterResults($event) {
        this.filter = $event.filter;
        this.filteredTodos = this.todos; 
        if (this.filter === "active") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed !== true);
          } else if (this.filter === "completed") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed === true);
          }
      }
    
      clearCompleted() {
        const CLEAR_COMPLETED = gql`
        mutation clearCompleted {
          delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
            affected_rows
          }
        }
      `;
        this.apollo.mutate({
          mutation: CLEAR_COMPLETED,
          optimisticResponse: {},
          update: (cache, {data}) => {
            const existingTodos : any = cache.readQuery({ query: GET_MY_TODOS });
            const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
            cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
          },
        }).subscribe(({ data, loading }) => {
          console.log('got something clear completed', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
}

// community/learn/graphql-tutorials/tutorials/react-apollo/app-final/src/components/Todo/TodoPrivateList.js
import React, { Component, Fragment } from "react";
import {Query} from 'react-apollo';
import gql from 'graphql-tag';

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

class TodoPrivateList extends Component {
  constructor(props) {
    super(props);

    this.state = {
      filter: "all",
      clearInProgress: false
    };

    this.filterResults = this.filterResults.bind(this);
    this.clearCompleted = this.clearCompleted.bind(this);

    // Set the apollo client
    this.client = props.client;
  }

  filterResults(filter) {
    this.setState({
      ...this.state,
      filter: filter
    });
  }

  clearCompleted() {

    // Remove all the todos that are completed
    const CLEAR_COMPLETED = gql`
      mutation clearCompleted {
        delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
          affected_rows
        }
      }
    `;

    this.client.mutate({
      mutation: CLEAR_COMPLETED,
      optimisticResponse: {},
      update: (cache, {data}) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
        cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
      }
    });
  }

  render() {
    const {todos} = this.props;

    let filteredTodos = todos;
    if (this.state.filter === "active") {
      filteredTodos = todos.filter(todo => todo.is_completed !== true);
    } else if (this.state.filter === "completed") {
      filteredTodos = todos.filter(todo => todo.is_completed === true);
    }

    const todoList = [];
    filteredTodos.forEach((todo, index) => {
      todoList.push(
        <TodoItem
          key={index}
          index={index}
          todo={todo}
        />
      );
    });

    return (
      <Fragment>
        <div className="todoListWrapper">
          <ul>
            { todoList }
          </ul>
        </div>

        <TodoFilters
          todos={filteredTodos}
          currentFilter={this.state.filter}
          filterResultsFn={this.filterResults}
          clearCompletedFn={this.clearCompleted}
          clearInProgress={this.state.clearInProgress}
        />
      </Fragment>
    );
  }
}

const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
}`;

const TodoPrivateListQuery = () => {
  return (
    <Query query={GET_MY_TODOS}>
      {({ loading, error, data, client}) => {
        if (loading) {
          return (<div>Loading...</div>);
        }
        if (error) {
          console.error(error);
          return (<div>Error!</div>);
        }
        return (<TodoPrivateList client={client} todos={data.todos} />);
      }}
    </Query>
  );
};
export default TodoPrivateListQuery;
export {GET_MY_TODOS};
