// community/learn/graphql-tutorials/tutorials/vue-apollo/app-final/src/components/TodoPublicList.vue
<template>
  <div>
    <div class="todoListwrapper">
      <div class="loadMoreSection" v-if="newTodosCount" v-on:click="loadMoreClicked">
        New tasks have arrived! ({{ newTodosCount }})
      </div>
      <TodoItem 
        v-bind:todos="todos" 
        v-bind:type="type" 
      />
      <div class="loadMoreSection" v-if="olderTodosAvailable" v-on:click="loadOlderClicked">
        Load older tasks
      </div>
    </div>
  </div>
</template>

<script>
import TodoItem from "../components/TodoItem";
import TodoFilters from "../components/TodoFilters";
import gql from "graphql-tag";
const NOTIFY_NEW_PUBLIC_TODOS = gql`
  subscription notifyNewPublicTodos {
    todos(
      where: { is_public: { _eq: true }} 
      order_by: { created_at: desc }
      limit: 1
    ) {
      id
      title
      created_at
    }
  }
`;
const GET_OLD_PUBLIC_TODOS = gql`
  query getOldPublicTodos($oldestTodoId: Int) {
    todos(
      where: { is_public: { _eq: true }, id: { _lt: $oldestTodoId } }
      limit: 7
      order_by: { created_at: desc }
    ) {
      id
      title
      created_at
      is_public
      user {
        name
      }
    }
  }
`;
const GET_NEW_PUBLIC_TODOS = gql`
  query getNewPublicTodos($latestVisibleId: Int!) {
    todos(
      where: { is_public: { _eq: true }, id: { _gt: $latestVisibleId } }
      order_by: { created_at: desc }
    ) {
      id
      title
      created_at
      is_public
      user {
        name
      }
    }
  }
`;
export default {
  components: {
    TodoItem, TodoFilters
  },
  data: function() {
    return {
      olderTodosAvailable: true,
      newTodosCount: 0,
      limit: 7,
      todos: [],
      type: "public"
    }
  },
  mounted() {
    const that = this;
    this.$apollo
      .query({
        query: GET_OLD_PUBLIC_TODOS
      })
      .then(data => {
        this.todos = data.data.todos;
        // start a subscription
        this.$apollo
          .subscribe({
            query: NOTIFY_NEW_PUBLIC_TODOS,
          })
          .subscribe({
            next(data) {
              if (data.data.todos.length) {
                // check if the received todo is already present
                if(data.data.todos[0].id !== that.todos[0].id) {
                  that.newTodosCount = that.newTodosCount + data.data.todos.length;
                }
              }
            },
            error(err) {
              console.error("err", err);
            }
          });
      });
  },
  methods: {
    loadMoreClicked: function() {
      this.newTodosCount = 0;
      this.$apollo
        .query({
          query: GET_NEW_PUBLIC_TODOS,
          variables: {
            latestVisibleId: this.todos.length ? this.todos[0].id : null
          }
        })
        .then(data => {
          if (data.data.todos.length) {
            const mergedTodos = data.data.todos.concat(this.todos);
            // update state with new todos
            this.todos = mergedTodos;
          }
        });
    },
    loadOlderClicked: function() {
      this.$apollo
        .query({
          query: GET_OLD_PUBLIC_TODOS,
          variables: {
            oldestTodoId: this.todos.length
              ? this.todos[this.todos.length - 1].id
              : null
          }
        })
        .then(data => {
          if (data.data.todos.length) {
            const mergedTodos = this.todos.concat(data.data.todos);
            // update state with new todos
            this.todos = mergedTodos;
          } else {
            this.olderTodosAvailable = false;
          }
        });
    },
  }
}
</script>

// community/learn/graphql-tutorials/tutorials/react-apollo/app-final/src/components/Todo/TodoPublicList.js
import React, { Component, Fragment } from 'react';
import {Subscription, withApollo} from 'react-apollo';
import gql from 'graphql-tag';
import TaskItem from './TaskItem';

class _TodoPublicList extends Component {
  constructor(props) {
    super(props);

    this.state = {
      olderTodosAvailable: props.latestTodo ? true : false,
      newTodosCount: 0,
      error: false,
      todos: [],
    };

    this.loadNew = this.loadNew.bind(this);
    this.loadOlder = this.loadOlder.bind(this);

    this.client = props.client;
    this.oldestTodoId = props.latestTodo ? (props.latestTodo.id + 1) : 0;
    this.newestTodoId = props.latestTodo ? props.latestTodo.id : 0;
  }

  loadNew() {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos ($latestVisibleId: Int) {
        todos(where: { is_public: { _eq: true}, id: {_gt: $latestVisibleId}}, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

    this.client.query({
      query: GET_NEW_PUBLIC_TODOS,
      variables: {latestVisibleId: this.state.todos.length ? this.state.todos[0].id : null}
    })
      .then(({data}) => {
        this.newestTodoId = data.todos[0].id;
        this.setState({todos: [...data.todos, ...this.state.todos], newTodosCount: 0});
      })
      .catch(error => {
        console.error(error);
        this.setState({error: true});
      });
  }

  loadOlder() {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos ($oldestTodoId: Int!) {
        todos (where: { is_public: { _eq: true}, id: {_lt: $oldestTodoId}}, limit: 7, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }`;

    this.client.query({
      query: GET_OLD_PUBLIC_TODOS,
      variables: {oldestTodoId: (this.oldestTodoId)}
    })
      .then(({data}) => {
        if (data.todos.length) {
          this.oldestTodoId = data.todos[data.todos.length - 1].id;
          this.setState({todos: [...this.state.todos, ...data.todos]});
        } else {
          this.setState({olderTodosAvailable: false});
        }
      })
      .catch(error => {
        console.error(error);
        this.setState({error: true});
      });
  }

  componentDidUpdate(prevProps) {
    // Do we have a new todo available?
    if (this.props.latestTodo && this.props.latestTodo.id > this.newestTodoId) {
      this.newestTodoId = this.props.latestTodo.id;
      this.setState({newTodosCount: this.state.newTodosCount + 1});
    }
  }

  componentDidMount() {
    this.loadOlder();
  }

  render() {

    let todos = this.state.todos;

    const todoList = (
      <ul>
        {
          todos.map((todo, index) => {
            return (
              <TaskItem
                key={index}
                index={index}
                todo={todo}
              />
            );
          })
        }
      </ul>
    );

    let newTodosNotification = '';
    if (this.state.newTodosCount) {
      newTodosNotification = (
        <div className={"loadMoreSection"} onClick={this.loadNew}>
          New tasks have arrived! ({this.state.newTodosCount.toString()})
        </div>
      );
    }

    const olderTodosMsg = (
      <div className={"loadMoreSection"} onClick={this.loadOlder}>
        { this.state.olderTodosAvailable ? 'Load older tasks' : 'No more public tasks!'}
      </div>
    );

    return (
      <Fragment>
        <div className="todoListWrapper">
          { newTodosNotification }

          { todoList }

          { olderTodosMsg }
        </div>
      </Fragment>
    );
  }
}

const TodoPublicList = withApollo(_TodoPublicList);

// Run a subscription to get the latest public todo
const NOTIFY_NEW_PUBLIC_TODOS = gql`
  subscription notifyNewPublicTodos {
    todos (where: { is_public: { _eq: true}}, limit: 1, order_by: {created_at: desc }) {
      id
      created_at
    }
  }
`;
const TodoPublicListSubscription = () => {
  return (
    <Subscription subscription={NOTIFY_NEW_PUBLIC_TODOS}>
      {({loading, error, data}) => {
        if (loading) {
          return (<span>Loading...</span>);
        }
        if (error) {
          return (<span>Error</span>);
        }
        return (<TodoPublicList latestTodo={data.todos.length ? data.todos[0] : null} />);
      }}
    </Subscription>
  );
};
export default TodoPublicListSubscription;
