// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoInput.ts
import { Component, OnInit, Input } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

import {GET_MY_TODOS} from './TodoPrivateList';

const ADD_TODO = gql `
  mutation ($todo: String!, $isPublic: Boolean!) {
    insert_todos(objects: {title: $todo, is_public: $isPublic}) {
      affected_rows
      returning {
        id
        title
        created_at
        is_completed
      }
    }
  }
 `;

@Component({  
    selector: 'TodoInput',  
    templateUrl: './TodoInput.template.html',  
  }) 

export class TodoInput {
    @Input('isPublic') isPublic: any = false;
    todoInput: any= '';
    loading: boolean = true;
    
    constructor(private apollo: Apollo) {}

    addTodo(e) {
      e.preventDefault();
      this.apollo.mutate({
        mutation: ADD_TODO,
        variables: {
          todo: this.todoInput,
          isPublic: this.isPublic 
        },
        update: (cache, {data}) => {
          
          if(this.isPublic) return null;
          
          const existingTodos : any = cache.readQuery({
            query: GET_MY_TODOS
          });

          const newTodo = data.insert_todos.returning[0];
          cache.writeQuery({
            query: GET_MY_TODOS,
            data: {todos: [newTodo, ...existingTodos.todos]}
          });
        },
        
      }).subscribe(({ data, loading }) => {
        this.loading = loading;
        this.todoInput = '';
        console.log('got data add todo', data);
      },(error) => {
        console.log('there was an error sending the query', error);
      });
    }
}

// community/learn/graphql-tutorials/tutorials/react-apollo/app-final/src/components/Todo/TodoInput.js
import React, {useState} from 'react';
import {Mutation } from 'react-apollo';
import gql from 'graphql-tag';
import {GET_MY_TODOS} from './TodoPrivateList';

const ADD_TODO = gql `
  mutation ($todo: String!, $isPublic: Boolean!) {
    insert_todos(objects: {title: $todo, is_public: $isPublic}) {
      affected_rows
      returning {
        id
        title
        created_at
        is_completed
      }
    }
  }
`;

const TodoInput = ({isPublic = false}) => {
  let input;

  const [todoInput, setTodoInput] = useState('');

  const updateCache = (cache, {data}) => {
    // If this is for the public feed, do nothing
    if (isPublic) {
      return null;
    }

    // Fetch the todos from the cache
    const existingTodos = cache.readQuery({
      query: GET_MY_TODOS
    });

    // Add the new todo to the cache
    const newTodo = data.insert_todos.returning[0];
    cache.writeQuery({
      query: GET_MY_TODOS,
      data: {todos: [newTodo, ...existingTodos.todos]}
    });
  };

  const resetInput = () => {
    setTodoInput('');
    input.focus();
  };

  return (
    <Mutation mutation={ADD_TODO} update={updateCache} onCompleted={resetInput}>
      {(addTodo, {loading, data}) => {
        return (
          <form className="formInput" onSubmit={(e)=> {
            e.preventDefault();
            addTodo({variables: {todo: todoInput, isPublic }});
          }}>
          <input className="input"
            value={todoInput}
            disabled={loading}
            ref={n => (input = n)}
            onChange={e => (setTodoInput(e.target.value))}
            />
            <i className="inputMarker fa fa-angle-right" />
          </form>
        );
      }}
    </Mutation>
  );
};

export default TodoInput;
