// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoPublicList.ts
import { Component, OnInit, Input } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag'; 

 // Run a subscription to get the latest public todo
 const NOTIFY_NEW_PUBLIC_TODOS = gql`
 subscription notifyNewPublicTodos {
   todos (where: { is_public: { _eq: true}}, limit: 1, order_by: {created_at: desc }) {
     id
     created_at
   }
 }
 `;

@Component({  
    selector: 'TodoPublicList',  
    templateUrl: './TodoPublicList.template.html',  
  }) 

export class TodoPublicList implements OnInit{
          olderTodosAvailable= true;
          newTodosCount = 0;
          oldestTodoId;
          newestTodoId;
          todos= [];
          loading: boolean = true;

      constructor(private apollo: Apollo) {}

      ngOnInit() {
        this.getNotifications();
      }

      getNotifications() {
        this.apollo.subscribe({
          query: NOTIFY_NEW_PUBLIC_TODOS,
        }).subscribe(({ data, loading }) => {
          this.loading = loading;
          if(data) {
            const latestTodo = data.todos.length ? data.todos[0] : null;
            this.olderTodosAvailable = latestTodo? true: false;
            this.oldestTodoId=latestTodo? (latestTodo.id +1) : 0 ;
            if (latestTodo && latestTodo.id > this.newestTodoId) {
              this.newestTodoId = latestTodo.id;
              this.newTodosCount = this.newTodosCount +1;
            } else {
              this.newestTodoId=latestTodo? latestTodo.id : 0;
              this.loadOlder();
            }
             
          }
          console.log('got data ', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
    
      loadNew() {
        const GET_NEW_PUBLIC_TODOS = gql`
        query getNewPublicTodos ($latestVisibleId: Int!) {
          todos(where: { is_public: { _eq: true}, id: {_gt: $latestVisibleId}}, order_by: { created_at: desc }) {
            id
            title
            created_at
            user {
              name
            }
          }
        }
      `;
      this.apollo.watchQuery({
        query: GET_NEW_PUBLIC_TODOS,
        variables: {latestVisibleId: this.todos[0].id}
      })
      .valueChanges
      .subscribe(({ data, loading }) => {
        const todosData : any = data;
        if(todosData) {
          this.newestTodoId = todosData.todos[0].id;
          this.todos = [...todosData.todos, ...this.todos]
          this.newTodosCount=0;
        }
        console.log('got data ', data);
      },(error) => {
        console.log('there was an error sending the query', error);
      });
      }
    
      loadOlder() {
      const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos ($oldestTodoId: Int!) {
        todos (where: { is_public: { _eq: true}, id: {_lt: $oldestTodoId}}, limit: 7, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }`;
    this.apollo.watchQuery({
      query: GET_OLD_PUBLIC_TODOS,
      variables: {oldestTodoId: this.oldestTodoId}
    })
    .valueChanges
    .subscribe(({ data, loading }) => {
      const todosData : any = data;
      if(todosData) {
        if (todosData.todos.length) {
          this.oldestTodoId = todosData.todos[todosData.todos.length - 1].id;
          this.todos = [...this.todos, ...todosData.todos]
        } else {
          this.olderTodosAvailable = false;
        }
      }
      console.log('got data ', data);
    },(error) => {
      console.log('there was an error sending the query', error);
    });
      }
    
}

// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/typescript-final/src/components/Todo/TodoPublicList.tsx
import React, { Fragment, useState, useEffect, useRef } from "react";
import { useSubscription, useApolloClient } from "@apollo/react-hooks";
import gql from "graphql-tag";
import TaskItem from "./TaskItem";

import { 
  GetOldPublicTodosQuery,
  GetOldPublicTodosQueryVariables
} from '../../generated/graphql';

const TodoPublicList = (props: any) => {
  const [olderTodosAvailable, setOlderTodosAvailable] = useState(props.latestTodo ? true : false)
  const [newTodosCount, setNewTodosCount] = useState(0)
  const [error, setError] = useState(false);
  const [todos, setTodos] = useState<GetOldPublicTodosQuery["todos"]>([]);

  let oldestTodoId = useRef(props.latestTodo ? props.latestTodo.id + 1 : 0);
  let newestTodoId = useRef(props.latestTodo ? props.latestTodo.id : 0);
  if(todos && todos.length) {
    oldestTodoId.current = todos[todos.length - 1].id
    newestTodoId.current = todos[0].id;
  }

  const client = useApolloClient();

  const loadOlder = async () => {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos($oldestTodoId: Int!) {
        todos(
          where: { is_public: { _eq: true }, id: { _lt: $oldestTodoId } }
          limit: 7
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

    const { data, networkStatus } = await client.query<GetOldPublicTodosQuery, GetOldPublicTodosQueryVariables>({
      query: GET_OLD_PUBLIC_TODOS,
      variables: { oldestTodoId: oldestTodoId.current }
    });

    if (data.todos && data.todos.length) {
      setTodos(prevTodos => {
        if(prevTodos) {
          return [...prevTodos, ...data.todos];
        } else {
          return data.todos;
        }
      });
      oldestTodoId.current = data.todos[data.todos.length - 1].id;
    } else {
      setOlderTodosAvailable(false);
    }
    if (networkStatus === 8) {
      console.error(data);
      setError(true);
    }
  };

  const loadNew = async () => {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos($latestVisibleId: Int) {
        todos(
          where: { is_public: { _eq: true }, id: { _gt: $latestVisibleId } }
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

    const { data, networkStatus } = await client.query({
      query: GET_NEW_PUBLIC_TODOS,
      variables: {
        latestVisibleId: newestTodoId.current
      }
    });

    if (data && data.todos) {
      setTodos(prevState => {
        console.log(prevState);
        if(prevState) {
          return [...data.todos, ...prevState]
        } else {
          return data.todos;
        }
      });
      setNewTodosCount(0);
      newestTodoId.current = data.todos[0].id;
    }
    if (networkStatus === 8) {
      console.error(data);
      setError(true);
    }
  };


  useEffect(() => {
    loadOlder();
    // eslint-disable-next-line
  }, []);

  useEffect(
    () => {
      if (props.latestTodo && props.latestTodo.id > newestTodoId.current) {
        setNewTodosCount(n => n + 1);
        newestTodoId.current = props.latestTodo.id;
      }
    },
    [props.latestTodo]
  );

  if(error) {
    return (<div>Error...</div>);
  }

  return (
    <Fragment>
      <div className="todoListWrapper">
        {newTodosCount !== 0 && (
          <div className={"loadMoreSection"} onClick={() => loadNew()}>
            New tasks have arrived! ({newTodosCount.toString()})
          </div>
        )}

        <ul>
          {todos &&
            todos.map((todo, index) => {
              return <TaskItem key={index} index={index} todo={todo} />;
            })}
        </ul>

        <div className={"loadMoreSection"} onClick={() => loadOlder()}>
          {olderTodosAvailable
            ? "Load older tasks"
            : "No more public tasks!"}
        </div>
      </div>
    </Fragment>
  );
};

const TodoPublicListSubscription = () => {
  // Run a subscription to get the latest public todo
  const NOTIFY_NEW_PUBLIC_TODOS = gql`
    subscription notifyNewPublicTodos {
      todos(
        where: { is_public: { _eq: true } }
        limit: 1
        order_by: { created_at: desc }
      ) {
        id
        created_at
      }
    }
  `;

  const { loading, error, data } = useSubscription(NOTIFY_NEW_PUBLIC_TODOS);
  if (loading) {
    return <span>Loading...</span>;
  }
  if (error) {
    return <span>Error</span>;
  }
  return (
    <TodoPublicList latestTodo={data.todos.length ? data.todos[0] : null} />
  );
};

export default TodoPublicListSubscription;
