// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoPrivateList.ts
import { Component, OnInit  } from '@angular/core';

import {TodoItem} from "./TodoItem";
import {TodoFilters} from "./TodoFilters";
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

export const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
 }`;

@Component({  
    selector: 'TodoPrivateList',  
    templateUrl: './TodoPrivateList.template.html'
  }) 

export class TodoPrivateList implements OnInit {
    
          filter = "all";
          clearInProgress= false;
          todos= [];
          filteredTodos: any;
          loading: boolean = true;


          constructor(private apollo: Apollo) {}

          ngOnInit() {
            this.apollo.watchQuery<any>({
              query: GET_MY_TODOS
            })
              .valueChanges
              .subscribe(({ data, loading }) => {
                this.loading = loading;
                this.todos = data.todos;
                this.filteredTodos = this.todos; 
              });
          }
    
      filterResults($event) {
        this.filter = $event.filter;
        this.filteredTodos = this.todos; 
        if (this.filter === "active") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed !== true);
          } else if (this.filter === "completed") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed === true);
          }
      }
    
      clearCompleted() {
        const CLEAR_COMPLETED = gql`
        mutation clearCompleted {
          delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
            affected_rows
          }
        }
      `;
        this.apollo.mutate({
          mutation: CLEAR_COMPLETED,
          optimisticResponse: {},
          update: (cache, {data}) => {
            const existingTodos : any = cache.readQuery({ query: GET_MY_TODOS });
            const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
            cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
          },
        }).subscribe(({ data, loading }) => {
          console.log('got something clear completed', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
}

// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/typescript-final/src/components/Todo/TodoPrivateList.tsx
import React, { Fragment, useState } from "react";
import gql from "graphql-tag";
import { useQuery, useMutation } from "@apollo/react-hooks";

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

import { 
  GetMyTodosQuery,
  ClearCompletedMutation
} from '../../generated/graphql';

const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
    }
  }
`;

 const CLEAR_COMPLETED = gql`
  mutation clearCompleted {
    delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
      affected_rows
    }
  }
`;

const TodoPrivateList = () => {

  const [filter, setFilter] = useState<string>("all");
  const { loading, error, data } = useQuery<GetMyTodosQuery>(GET_MY_TODOS);
  const [clearTodos] = useMutation<ClearCompletedMutation>(
      CLEAR_COMPLETED, 
      {
        update(cache, { data }) {
          const existingTodos: any = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
          const newTodos = existingTodos.todos.filter((t:any) => (!t.is_completed));
          cache.writeQuery<GetMyTodosQuery>({query:GET_MY_TODOS, data: {todos: newTodos}});
        }
      });

  const filterResults = (filter: string): void => {
    setFilter(filter);
  };

  const clearCompleted = (): void => {
    clearTodos();
  }

  if(loading) {
    return (<div>Loading...</div>);
  }
  if(error || !data) {
    return (<div>Error...</div>);
  }

  let filteredTodos = data.todos;
  console.log(filter);
  if (filter === "active") {
    filteredTodos = data.todos.filter(todo => todo.is_completed !== true);
  } else if (filter === "completed") {
    filteredTodos = data.todos.filter(todo => todo.is_completed === true);
  }

  const todoList = [] as any;
  filteredTodos.forEach((todo: any, index: number) => {
    todoList.push(
      <TodoItem
        key={'item'+index}
        index={index}
        todo={todo}
      />
    );
  });

  return (
    <Fragment>
      <div className="todoListWrapper">
        <ul>
          { todoList }
        </ul>
      </div>

      <TodoFilters
        todos={filteredTodos}
        currentFilter={filter}
        filterResultsFn={filterResults}
        clearCompletedFn={clearCompleted}
      />
    </Fragment>
  );
}

export default TodoPrivateList;
export { GET_MY_TODOS };
