// community/learn/graphql-tutorials/tutorials/react-apollo-hooks/app-final/src/components/Todo/TodoPrivateList.js
import React, { Fragment, useState } from "react";
import { useQuery, useMutation } from "@apollo/react-hooks";
import gql from "graphql-tag";

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(
      where: { is_public: { _eq: false } }
      order_by: { created_at: desc }
    ) {
      id
      title
      created_at
      is_completed
    }
  }
`;

// Remove all the todos that are completed
const CLEAR_COMPLETED = gql`
  mutation clearCompleted {
    delete_todos(
      where: { is_completed: { _eq: true }, is_public: { _eq: false } }
    ) {
      affected_rows
    }
  }
`;

const TodoPrivateList = props => {
  const [state, setState] = useState({
    filter: "all",
    clearInProgress: false
  });

  const filterResults = filter => {
    setState({
      ...state,
      filter: filter
    });
  };

  const [clearCompletedTodos] = useMutation(CLEAR_COMPLETED);

  const clearCompleted = () => {
    clearCompletedTodos({
      optimisticResponse: {},
      update: (cache, { data }) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter(t => !t.is_completed);
        cache.writeQuery({ query: GET_MY_TODOS, data: { todos: newTodos } });
      }
    });
  };

  const { todos } = props;

  let filteredTodos = todos;
  if (state.filter === "active") {
    filteredTodos = todos.filter(todo => todo.is_completed !== true);
  } else if (state.filter === "completed") {
    filteredTodos = todos.filter(todo => todo.is_completed === true);
  }

  const todoList = [];
  filteredTodos.forEach((todo, index) => {
    todoList.push(<TodoItem key={index} index={index} todo={todo} />);
  });

  return (
    <Fragment>
      <div className="todoListWrapper">
        <ul>{todoList}</ul>
      </div>

      <TodoFilters
        todos={filteredTodos}
        currentFilter={state.filter}
        filterResultsFn={filterResults}
        clearCompletedFn={clearCompleted}
        clearInProgress={state.clearInProgress}
      />
    </Fragment>
  );
};

const TodoPrivateListQuery = () => {
  const { loading, error, data } = useQuery(GET_MY_TODOS);

  if (loading) {
    return <div>Loading...</div>;
  }
  if (error) {
    console.error(error);
    return <div>Error!</div>;
  }
  return <TodoPrivateList todos={data.todos} />;
};
export default TodoPrivateListQuery;
export { GET_MY_TODOS };

// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoPrivateList.ts
import { Component, OnInit  } from '@angular/core';

import {TodoItem} from "./TodoItem";
import {TodoFilters} from "./TodoFilters";
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

export const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
 }`;

@Component({  
    selector: 'TodoPrivateList',  
    templateUrl: './TodoPrivateList.template.html'
  }) 

export class TodoPrivateList implements OnInit {
    
          filter = "all";
          clearInProgress= false;
          todos= [];
          filteredTodos: any;
          loading: boolean = true;


          constructor(private apollo: Apollo) {}

          ngOnInit() {
            this.apollo.watchQuery<any>({
              query: GET_MY_TODOS
            })
              .valueChanges
              .subscribe(({ data, loading }) => {
                this.loading = loading;
                this.todos = data.todos;
                this.filteredTodos = this.todos; 
              });
          }
    
      filterResults($event) {
        this.filter = $event.filter;
        this.filteredTodos = this.todos; 
        if (this.filter === "active") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed !== true);
          } else if (this.filter === "completed") {
            this.filteredTodos = this.todos.filter(todo => todo.is_completed === true);
          }
      }
    
      clearCompleted() {
        const CLEAR_COMPLETED = gql`
        mutation clearCompleted {
          delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
            affected_rows
          }
        }
      `;
        this.apollo.mutate({
          mutation: CLEAR_COMPLETED,
          optimisticResponse: {},
          update: (cache, {data}) => {
            const existingTodos : any = cache.readQuery({ query: GET_MY_TODOS });
            const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
            cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
          },
        }).subscribe(({ data, loading }) => {
          console.log('got something clear completed', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
}
