// community/learn/graphql-tutorials/tutorials/react-apollo-hooks/app-final/src/components/Todo/TodoPublicList.js
import React, { Fragment, useState, useEffect } from 'react';
import { useSubscription, useApolloClient } from '@apollo/react-hooks';
import gql from 'graphql-tag';
import TaskItem from './TaskItem';

const TodoPublicList = (props) => {
  const [state, setState] = useState({
    olderTodosAvailable: props.latestTodo ? true : false,
    newTodosCount: 0,
    error: false,
    todos: [],
    oldestTodoId: props.latestTodo ? (props.latestTodo.id + 1) : 0,
    newestTodoId: props.latestTodo ? props.latestTodo.id : 0, 
  });
  
  const client = useApolloClient();

  useEffect(() => {
    loadOlder();
  }, []);

  useEffect(() => {
    if (props.latestTodo && props.latestTodo.id > state.newestTodoId) {
      setState({...state, newestTodoId: props.latestTodo.id, newTodosCount: state.newTodosCount + 1});
    }
  }, [props.latestTodo]);

  const loadOlder = async () => {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos ($oldestTodoId: Int!) {
        todos (where: { is_public: { _eq: true}, id: {_lt: $oldestTodoId}}, limit: 7, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }`;

    const { error, data} = await client.query({query: GET_OLD_PUBLIC_TODOS, 
      variables: {oldestTodoId: state.oldestTodoId}
    });

          if (data.todos.length) {
            setState({...state , oldestTodoId: data.todos[data.todos.length - 1].id, todos: [...state.todos, ...data.todos]});
          } else {
            setState({...state, olderTodosAvailable: false});
          }
        if (error) {
          console.error(error);
          setState({...state, error: true});
        }        
  }

  const loadNew = async () => {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos ($latestVisibleId: Int) {
        todos(where: { is_public: { _eq: true}, id: {_gt: $latestVisibleId}}, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

const { error, data } = await client.query({query: GET_NEW_PUBLIC_TODOS,
  variables: {latestVisibleId: state.todos.length ? state.todos[0].id : null} 
});   

      if(data) {  
        setState({...state, newestTodoId:data.todos[0].id, todos: [...data.todos, ...state.todos], newTodosCount: 0});
      }
      if(error){
        console.error(error);
        setState({...state, error: true});
      }
  }

    return (
      <Fragment>
        <div className="todoListWrapper">
        {state.newTodosCount !==0 && <div className={"loadMoreSection"} onClick={loadNew}>
          New tasks have arrived! ({state.newTodosCount.toString()})
        </div>}

          <ul>
        {
          state.todos && state.todos.map((todo, index) => {
            return (
              <TaskItem
                key={index}
                index={index}
                todo={todo}
              />
            );
          })
        }
      </ul> 

      <div className={"loadMoreSection"} onClick={loadOlder}>
        { state.olderTodosAvailable ? 'Load older tasks' : 'No more public tasks!'}
      </div> 
        </div>
      </Fragment>
    );
} 

// Run a subscription to get the latest public todo
const NOTIFY_NEW_PUBLIC_TODOS = gql`
  subscription notifyNewPublicTodos {
    todos (where: { is_public: { _eq: true}}, limit: 1, order_by: {created_at: desc }) {
      id
      created_at
    }
  }
`;

const TodoPublicListSubscription = () => {
  const { loading, error, data } = useSubscription(NOTIFY_NEW_PUBLIC_TODOS);
        if (loading) {
          return (<span>Loading...</span>);
        }
        if (error) {
          return (<span>Error</span>);
        }
        return (<TodoPublicList latestTodo={data.todos.length ? data.todos[0] : null} />);
};
export default TodoPublicListSubscription;

// community/learn/graphql-tutorials/tutorials/angular-apollo/app-final/src/app/Todo/TodoPublicList.ts
import { Component, OnInit, Input } from '@angular/core';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag'; 

 // Run a subscription to get the latest public todo
 const NOTIFY_NEW_PUBLIC_TODOS = gql`
 subscription notifyNewPublicTodos {
   todos (where: { is_public: { _eq: true}}, limit: 1, order_by: {created_at: desc }) {
     id
     created_at
   }
 }
 `;

@Component({  
    selector: 'TodoPublicList',  
    templateUrl: './TodoPublicList.template.html',  
  }) 

export class TodoPublicList implements OnInit{
          olderTodosAvailable= true;
          newTodosCount = 0;
          oldestTodoId;
          newestTodoId;
          todos= [];
          loading: boolean = true;

      constructor(private apollo: Apollo) {}

      ngOnInit() {
        this.getNotifications();
      }

      getNotifications() {
        this.apollo.subscribe({
          query: NOTIFY_NEW_PUBLIC_TODOS,
        }).subscribe(({ data, loading }) => {
          this.loading = loading;
          if(data) {
            const latestTodo = data.todos.length ? data.todos[0] : null;
            this.olderTodosAvailable = latestTodo? true: false;
            this.oldestTodoId=latestTodo? (latestTodo.id +1) : 0 ;
            if (latestTodo && latestTodo.id > this.newestTodoId) {
              this.newestTodoId = latestTodo.id;
              this.newTodosCount = this.newTodosCount +1;
            } else {
              this.newestTodoId=latestTodo? latestTodo.id : 0;
              this.loadOlder();
            }
             
          }
          console.log('got data ', data);
        },(error) => {
          console.log('there was an error sending the query', error);
        });
      }
    
      loadNew() {
        const GET_NEW_PUBLIC_TODOS = gql`
        query getNewPublicTodos ($latestVisibleId: Int!) {
          todos(where: { is_public: { _eq: true}, id: {_gt: $latestVisibleId}}, order_by: { created_at: desc }) {
            id
            title
            created_at
            user {
              name
            }
          }
        }
      `;
      this.apollo.watchQuery({
        query: GET_NEW_PUBLIC_TODOS,
        variables: {latestVisibleId: this.todos[0].id}
      })
      .valueChanges
      .subscribe(({ data, loading }) => {
        const todosData : any = data;
        if(todosData) {
          this.newestTodoId = todosData.todos[0].id;
          this.todos = [...todosData.todos, ...this.todos]
          this.newTodosCount=0;
        }
        console.log('got data ', data);
      },(error) => {
        console.log('there was an error sending the query', error);
      });
      }
    
      loadOlder() {
      const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos ($oldestTodoId: Int!) {
        todos (where: { is_public: { _eq: true}, id: {_lt: $oldestTodoId}}, limit: 7, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }`;
    this.apollo.watchQuery({
      query: GET_OLD_PUBLIC_TODOS,
      variables: {oldestTodoId: this.oldestTodoId}
    })
    .valueChanges
    .subscribe(({ data, loading }) => {
      const todosData : any = data;
      if(todosData) {
        if (todosData.todos.length) {
          this.oldestTodoId = todosData.todos[todosData.todos.length - 1].id;
          this.todos = [...this.todos, ...todosData.todos]
        } else {
          this.olderTodosAvailable = false;
        }
      }
      console.log('got data ', data);
    },(error) => {
      console.log('there was an error sending the query', error);
    });
      }
    
}
