// community/learn/graphql-tutorials/tutorials/react-apollo/app-final/src/components/Todo/TodoPrivateList.js
import React, { Component, Fragment } from "react";
import {Query} from 'react-apollo';
import gql from 'graphql-tag';

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

class TodoPrivateList extends Component {
  constructor(props) {
    super(props);

    this.state = {
      filter: "all",
      clearInProgress: false
    };

    this.filterResults = this.filterResults.bind(this);
    this.clearCompleted = this.clearCompleted.bind(this);

    // Set the apollo client
    this.client = props.client;
  }

  filterResults(filter) {
    this.setState({
      ...this.state,
      filter: filter
    });
  }

  clearCompleted() {

    // Remove all the todos that are completed
    const CLEAR_COMPLETED = gql`
      mutation clearCompleted {
        delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
          affected_rows
        }
      }
    `;

    this.client.mutate({
      mutation: CLEAR_COMPLETED,
      optimisticResponse: {},
      update: (cache, {data}) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
        cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
      }
    });
  }

  render() {
    const {todos} = this.props;

    let filteredTodos = todos;
    if (this.state.filter === "active") {
      filteredTodos = todos.filter(todo => todo.is_completed !== true);
    } else if (this.state.filter === "completed") {
      filteredTodos = todos.filter(todo => todo.is_completed === true);
    }

    const todoList = [];
    filteredTodos.forEach((todo, index) => {
      todoList.push(
        <TodoItem
          key={index}
          index={index}
          todo={todo}
        />
      );
    });

    return (
      <Fragment>
        <div className="todoListWrapper">
          <ul>
            { todoList }
          </ul>
        </div>

        <TodoFilters
          todos={filteredTodos}
          currentFilter={this.state.filter}
          filterResultsFn={this.filterResults}
          clearCompletedFn={this.clearCompleted}
          clearInProgress={this.state.clearInProgress}
        />
      </Fragment>
    );
  }
}

const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
}`;

const TodoPrivateListQuery = () => {
  return (
    <Query query={GET_MY_TODOS}>
      {({ loading, error, data, client}) => {
        if (loading) {
          return (<div>Loading...</div>);
        }
        if (error) {
          console.error(error);
          return (<div>Error!</div>);
        }
        return (<TodoPrivateList client={client} todos={data.todos} />);
      }}
    </Query>
  );
};
export default TodoPrivateListQuery;
export {GET_MY_TODOS};

// community/learn/graphql-tutorials/tutorials/vue-apollo/app-final/src/components/TodoPrivateList.vue
<template>
  <div>
    <div class="todoListwrapper">
      <TodoItem 
        v-bind:todos="filteredTodos" 
        v-bind:type="type" 
      />
    </div>
    <TodoFilters 
      v-bind:remainingTodos="remainingTodos" 
      v-bind:filterResults="filterResults" 
      v-bind:filterType="filterType"
      v-bind:type="type"
      v-bind:clearCompleted="clearCompleted"
    />
  </div>
</template>

<script>
import TodoItem from "../components/TodoItem";
import TodoFilters from "../components/TodoFilters";
import gql from "graphql-tag";
const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(
      where: { is_public: { _eq: false } }
      order_by: { created_at: desc }
    ) {
      id
      title
      created_at
      is_completed
    }
  }
`;
export default {
  components: {
    TodoItem, TodoFilters
  },
  data() {
    return {
      type: "private",
      filterType: "all",
      todos: []
    }
  },
  computed: {
    remainingTodos: function() {
      const activeTodos = this.todos !== undefined ? this.todos.filter((todo) => todo.is_completed !== true) : []
      return activeTodos.length
    },
    filteredTodos: function() {
      if (this.filterType === 'all') {
        return this.todos
      } else if(this.filterType === 'active') {
        return this.todos.filter((todo) => todo.is_completed !== true);
      } else if (this.filterType === 'completed') {
        return this.todos.filter((todo) => todo.is_completed === true);
      }
    }
  },
  methods: {
    filterResults: function(type) {
      if(type === 'active') {
        this.filterType = "active";
      } else if(type === 'completed') {
        this.filterType = "completed";
      } else {
        this.filterType = "all";
      }
    },
    clearCompleted: function() {
      const client = this.$apolloProvider.clients.defaultClient;
      const isOk = window.confirm("Are you sure?");
      if (isOk) {
        // Remove all the todos that are completed
        const CLEAR_COMPLETED = gql`
          mutation clearCompleted {
            delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
              affected_rows
            }
          }
        `;
        client
          .mutate({
            mutation: CLEAR_COMPLETED,
            update: (store, { data: { delete_todos } }) => {
              if (delete_todos.affected_rows) {
                const data = store.readQuery({
                  query: GET_MY_TODOS,
                });
                data.todos = data.todos.filter((todo) => todo.is_completed !== true);
                store.writeQuery({
                  query: GET_MY_TODOS,
                  data
                });
              }
            },
          })
          .catch(error => {
            console.error(error);
          });
      }
    }
  },
  apollo: {
    todos: {
      // graphql query
      query: GET_MY_TODOS,
    },
  },
}
</script>
