// community/learn/graphql-tutorials/tutorials/react-apollo-typescript/typescript-final/src/components/Todo/TodoItem.tsx
import * as React from 'react';
import gql from 'graphql-tag';
import { useMutation } from '@apollo/react-hooks';
import { GET_MY_TODOS } from './TodoPrivateList';
import { 
  Todos, 
  GetMyTodosQuery,
  RemoveTodoMutationFn,
} from '../../generated/graphql';

interface TodoItemType {
  index: number,
  todo: Todos
}

const TOGGLE_TODO = gql`
  mutation toggleTodo ($id: Int!, $isCompleted: Boolean!) {
    update_todos(where: {id: {_eq: $id}}, _set: {is_completed: $isCompleted}) {
      affected_rows
    }
  }
`;

const REMOVE_TODO = gql`
  mutation removeTodo ($id: Int!) {
    delete_todos(where: {id: {_eq: $id}}) {
      affected_rows
    }
  }
`;

const TodoItem = ({index, todo}: TodoItemType) => {

  const [todoUpdate] = useMutation(
    TOGGLE_TODO, 
    {
      update(cache, { data }) {
        const existingTodos: any = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.map((t:Todos) => {
          if (t.id === todo.id) {
            return({...t, is_completed: !t.is_completed});
          } else {
            return t;
          }
        });
        cache.writeQuery<GetMyTodosQuery>({
          query: GET_MY_TODOS,
          data: {todos: newTodos}
        });
      }
    }
  );

  const [todoRemove] = useMutation<RemoveTodoMutationFn>(
    REMOVE_TODO, 
    {
      update(cache, { data }) {
        const existingTodos: any = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter((t:Todos) => (t.id !== todo.id));
        cache.writeQuery<GetMyTodosQuery>({
          query: GET_MY_TODOS,
          data: {todos: newTodos}
        });
      }
    }
  );

  const removeTodo = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    todoRemove({
      variables: { id: todo.id },
    });
  };

  const toggleTodo = () => {
    todoUpdate({
      variables: { id: todo.id, isCompleted: !todo.is_completed },
      optimisticResponse: {
        __typename: "Mutation",
        update_todos: {
          __typename: "todos_mutation_response",
          id: todo.id,
          title: todo.title,
          is_completed: todo.is_completed,
          affected_rows: 1
        }
      }
    });
  };

  return (
    <li key={index}>
      <div className="view">
        <div className="round">
          <input
            checked={todo.is_completed}
            type="checkbox"
            id={todo.id.toString()}
            onChange={() => toggleTodo()}
          />
          <label htmlFor={todo.id.toString()}/>
        </div>
      </div>

      <div className={"labelContent" + (todo.is_completed ? " completed" : '')}>
        <div>
          {todo.title}
        </div>
      </div>

      <button className="closeBtn" onClick={(e) => removeTodo(e)}>
        x
      </button>
    </li>
  );
};

export default TodoItem;

// community/learn/graphql-tutorials/tutorials/vue-apollo/app-final/src/components/TodoItem.vue
<template>
  <ul>
    <li v-for="todo in todos" v-bind:key="todo.id">
      <div v-if="todo.is_public" class="userInfoPublic">
        @{{ todo.user.name }}
      </div>
      <div class="view" v-if="type === 'private'">
          <div v-if="todo.is_completed" class="round">
            <input
              type="checkbox"
              id="todo.id"
              checked="true"
            />
            <label 
              v-on:click="handleTodoToggle(todo)"
              htmlFor="todo.id"></label>
          </div>
          <div v-else class="round">
            <input
              type="checkbox"
              id="todo.id"
            />
            <label 
              v-on:click="handleTodoToggle(todo)"
              htmlFor="todo.id"></label>
          </div>
      </div>
      <div class="labelContent">
          <strike class="todoLabel" v-if="todo.is_completed">
            <div>
              {{ todo.title }}
            </div>
          </strike>
          <div v-else>
            {{ todo.title }}
          </div>
      </div>
      <button v-if="type === 'private'" v-on:click="handleTodoDelete(todo)" class="closeBtn"> x </button>
    </li>
  </ul>
</template>

<script>
  import gql from 'graphql-tag';
  import { GET_MY_TODOS } from "./TodoPrivateList.vue";
  const TOGGLE_TODO = gql`
    mutation update_todos($id: Int!, $isCompleted: Boolean!) {
      update_todos(where: { id: { _eq: $id } }, _set: { is_completed: $isCompleted }) {
        affected_rows
      }
    }
  `;
  const REMOVE_TODO = gql`
    mutation delete_todos($id: Int!) {
      delete_todos(where: { id: { _eq: $id } }) {
        affected_rows
      }
    }
  `;
  export default {
    props: ['todos', 'type'],
    methods: {
      handleTodoToggle: function (todo) {
        // update todo data in db here
        this.$apollo.mutate({
          mutation: TOGGLE_TODO,
          variables: {
           id: todo.id,
           isCompleted: !todo.is_completed
          },
          update: (store, { data: { update_todos } }) => {
            if (update_todos.affected_rows) {
              if (this.type === "private") {
                // Read the data from our cache for this query.
                const data = store.readQuery({
                  query: GET_MY_TODOS,
                });
                const toggledTodo = data.todos.find(t => t.id === todo.id);
                toggledTodo.is_completed = !todo.is_completed;
                store.writeQuery({
                  query: GET_MY_TODOS,
                  data
                });
              } 
            }
          },
          optimisticResponse: {
            __typename: 'Mutation',
            update_todos: {
              __typename: 'todos',
              id: todo.id,
              is_completed: !todo.is_completed,
              affected_rows: 1
            },
          }
        });
      },
      handleTodoDelete: function(todo) {
        // delete todo from db
        this.$apollo.mutate({
          mutation: REMOVE_TODO,
          variables: {
           id: todo.id,
          },
          update: (store, { data: { delete_todos } }) => {
            if (delete_todos.affected_rows) {
              if (this.type === "private") {
                const data = store.readQuery({
                  query: GET_MY_TODOS
                });
                data.todos = data.todos.filter(t => {
                  return t.id !== todo.id;
                });
                store.writeQuery({
                  query: GET_MY_TODOS,
                  data
                });
              }
            }
          },
        });
      }
    }
  }

</script>
