// community/sample-apps/vuejs-auth0-graphql/app/src/components/Callback.vue
<template>
  <div class="spinner">
    <img src="../assets/loading.svg" alt="Loading">
  </div>
</template>

<script>
export default {
  methods: {
    handleLoginEvent(data) {
      // this.$router.push(data.state.target || "/");
      window.location.href = data.state.target || "/";
    }
  },
  created() {
    this.$auth.handleAuthentication();
  }
};
</script>

<style scoped>
.spinner {
  position: absolute;
  display: flex;
  justify-content: center;
  height: 100vh;
  width: 100vw;
  background-color: white;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>

// community/learn/graphql-tutorials/tutorials/react-apollo-hooks/app-final/src/components/Auth/Callback.js
import React from "react";
import loading from "./loading.svg";

const Callback = () => {
  
    const style = {
      position: "absolute",
      display: "flex",
      justifyContent: "center",
      height: "100vh",
      width: "100vw",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "white"
    };

    return (
      <div style={style}>
        <img src={loading} alt="loading" />
      </div>
    );
  }

export default Callback;
