// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/OnlineUsers.vue
<template>
  <div class="sliderMenu grayBgColor">
    <div class="sliderHeader">
      Online users - {{ online_list.length }}
    </div>
    <div class="userInfo" v-for="user in online_list" v-bind:key="user.user.name">
      <div class="userImg">
        <i class="far fa-user" />
      </div>
      <div class="userName">
        {{ user.user.name }}
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        online_list: [
          { user: { name: "someUser1" }},
          { user: { name: "someUser2" }}
        ]
      };
    },
  }

</script>

// community/tutorials/react-apollo/ui-boilerplate/src/components/OnlineUsers/OnlineUsers.js
import React, { Component } from "react";

class OnlineUsers extends Component {
  render() {
    const data = {online_users: [{ name: "someUser1" }, { name: "someUser2" }]};
    return (
      <div className="sliderMenu grayBgColor">
        <div className="sliderHeader">
          Online users - {data.online_users.length}
        </div>
        {data.online_users.map((user, index) => {
          return (
            <div key={user.name} className="userInfo">
              <div className="userImg">
                <i className="far fa-user" />
              </div>
              <div
                data-test={index + "_" + user.name}
                className="userName"
              >
                {user.name}
              </div>
            </div>
          );
        })}
      </div>
    );
  }
}

export default OnlineUsers;
