// community/learn/graphql-tutorials/tutorials/vue-apollo/app-boilerplate/src/components/TodoInput.vue
<template>
  <div class="formInput">
    <input 
	class="input" 
	placeholder="What needs to be done?" 
	v-model="newTodo"
	@keyup.enter="addTodo"
    />
    <i class="downArrow fa fa-angle-right" />
  </div>
</template>

<script>
  export default {
    props: ['type'],
    data() {
      return {
        newTodo: '',
      }
    },
    methods: {
      addTodo: function () {
        // insert new todo into db
      },
    }
  }
</script>

// community/learn/graphql-tutorials/tutorials/react-apollo/app-boilerplate/src/components/Todo/TodoInput.js
import React from 'react';

const TodoInput = ({type}) => {
  return (
    <form className="formInput" onSubmit={(e) => {
      e.preventDefault();
    }}>
      <input
        className="input"
        data-test={type === "private" ? "input-private" : "input-public"}
        placeholder="What needs to be done?"
      />
      <i className="inputMarker fa fa-angle-right" />
    </form>
  );
}

export default TodoInput;
